alias mp+='cat {{ alias_directory }}/{{ item | basename() }}'

alias mp=multipass
alias mpl='mp list'
alias mpd='mp delete'
alias mpda='mp delete --all'
alias mpp='mp purge'
alias mpf='mp find'
alias mpe='mp exec'
alias mpi='mp info'
alias mpr='mp restart'
alias mpra='mp restart --all'
alias mps='mp start'
alias mpsa='mp start --all'
alias mpS='mp stop'
alias mpSa='mp stop --all'
alias mpsh='mp shell'
alias mph='mp help'

alias mpl_1c_2G_10g='mp launch -c 1 -m 2G -d 10G --bridged -n'
alias mpl_2c_4G_20g='mp launch -c 2 -m 4G -d 20G --bridged -n'
alias mpl_4c_8G_30g='mp launch -c 4 -m 8G -d 30G --bridged -n'
alias mpl_6c_12G_60g='mp launch -c 6 -m 12G -d 60G --bridged -n'
alias mpl_8c_16G_100g='mp launch -c 8 -m 16G -d 100G --bridged -n'
