alias tf+='cat {{ alias_directory }}/{{ item | basename() }}'

alias tf=terraform

alias tfS='tf show'
alias tfr='tf refresh'
alias tfi='tf init'
alias tfim='tf init -migrate-state'
alias tfir='tf init -reconfigure'
alias tfiu='tf init -upgrade'
alias tfo='tf output'
alias tfor='tf output -raw'
alias tfoj='tf output -json'
alias tfv='tf validate'
alias tfV='tf version'
alias tff='tf fmt --recursive'
alias tfg='tf get'
alias tfaa='tf apply -auto-approve -input=false'
alias tfa='tf apply -input=false'
alias tfat='tf apply -input=false -target'
alias tfp='tf plan -input=false'
alias tfda='tf destroy -auto-approve -input=false'
alias tfd='tf destroy -input=false'
alias tfdt='tf destroy -input=false -target'
alias tft='tf taint'
alias tfu='tf untaint'
alias tfs='tf state'
alias tfsl='tf state list'
alias tfsp='tf state pull | less'
alias tfsr='tf state rm'
alias tfsm='tf state mv'
alias tfss='tf state show'
alias tfm='tf import'


alias tg=terragrunt
alias tga='tg apply -input=false'
alias tgaa='tg apply -auto-approve -input=false'
alias tgA='tg apply --all -input=false'
alias tgAa='tg apply --all -auto-approve -input=false'
alias tgd='tg destroy'
alias tgda='tg destroy -auto-approve'
alias tgD='tg destroy --all'
alias tgDa='tg destroy --all -auto-approve'
alias tgp='tg plan -input=false'
alias tgP='tg plan --all -input=false'
alias tgf='tg run --all -- fmt; tg hcl fmt --all'
alias tgv='tg validate-inputs --terragrunt-strict-validate'