#!/usr/bin/env bash

tmux new-session \; \
  split-window -v \; \
  split-window -v \; \
  split-window -v \; \
  split-window -v \; \
  split-window -h \; \
  split-window -h \; \
  select-pane -t 0 \; send-keys 'tsh ssh ianfritz@alwayson-asterisk-dgt-link-use2-1.prod.letsdowonders.io' C-m \; \
  select-pane -t 1 \; send-keys 'tsh ssh ianfritz@alwayson-asterisk-kmc-link-use2-1.prod.letsdowonders.io' C-m \; \
  select-pane -t 2 \; send-keys 'tsh ssh ianfritz@alwayson-asterisk-oh-link-use2-1.prod.letsdowonders.io' C-m \; \
  select-pane -t 3 \; send-keys 'tsh ssh ianfritz@alwayson-asterisk-ph-link-use2-1.prod.letsdowonders.io' C-m \; \
  select-pane -t 4 \; send-keys 'tsh ssh ianfritz@alwayson-asterisk-ph-wfh-link-use2-1.prod.letsdowonders.io' C-m \; \
  select-pane -t 5 \; send-keys 'tsh ssh ianfritz@alwayson-asterisk-sg-link-use2-1.prod.letsdowonders.io' C-m \; \
  select-pane -t 6 \; send-keys 'tsh ssh ianfritz@alwayson-asterisk-sg-wfh-link-use2-1.prod.letsdowonders.io' C-m \; \
  select-pane -t 0 \; \
  next-layout \; \
  next-layout
