- name: Install dnf packages
  become: true
  ansible.builtin.dnf:
    pkg:
      - git
      - curl
      - zip
      - jq
      - dnsutils
      - zsh
      - azure-cli
      - dnf-plugins-core

- name: Add docker repo
  become: true
  ansible.builtin.shell:
    cmd: dnf-3 config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

- name: Install docker
  become: true
  ansible.builtin.dnf:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

- name: Enable docker
  become: true
  ansible.builtin.systemd_service:
    name: docker
    enabled: true
    state: started

- name: Add user to docker group
  become: true
  ansible.builtin.user:
    name: u
    groups: docker
    append: true